import React from 'react'
import Head from 'next/head'
import styles from '../styles/About.module.css'
import { ImYoutube2, ImFacebook2 } from 'react-icons/im'
import { BiEnvelope } from 'react-icons/bi'
import { FaWhatsapp, FaFacebookF, FaInstagram, FaYoutube } from 'react-icons/fa'
import Link from 'next/link'

export default function About() {

    const youtubeChannel = () => {
        document.location.href = 'https://www.youtube.com/channel/UC5Lv5niABG4jKjCAi7PRw1A';
      }

      const instgramHandle = () => {
        document.location.href = 'https://www.instagram.com/the.carportal/';
      }

      const whatsappLink =() => {
        document.location.href = "https://wa.me/message/TBMCAPTHYDDTD1";
      }

    return (
        
        <>
        <Head>
        <title>CarPotal | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <main className={styles.main_about}>
                {/* <h2>About Us</h2> */}
                <p>Founded in 2020, The car portal is a space that talks about cars, a space where you find anything about cars and car related stuff Started as an Instagram blog, expanding the horizon to car sales, fun YouTube videos, cool car merch</p>
                <div className={styles.social__links}>
                    <div className={styles.single_link} onClick={youtubeChannel}>
                        <div className={styles.icon} style={{background: '#ff0000'}}>
                            <FaYoutube />
                        </div>
                        <div className={styles.text}>
                            Youtube
                        </div>
                    </div>
                    <div className={styles.single_link} onClick={whatsappLink}>
                        <div className={styles.icon} style={{background: '#25d366'}}>
                            <FaWhatsapp style={{fontSize: '40px'}}/>
                        </div>
                        <div className={styles.text}>
                            WhatsApp
                        </div>
                    </div>
                    <div className={styles.single_link} onClick={instgramHandle}> 
                        <div className={styles.icon} style={{background: '#dd2a7b'}}>
                            <FaInstagram />
                        </div>
                        <div className={styles.text}>
                            Instagram
                        </div>
                    </div>
                    <a href="mailto:thecarportalnet@gmail.com" className={styles.single_link} style={{background: '#f6fa1996'}}>
                        <div className={styles.icon} style={{background: '#f6fa19'}}>
                            <BiEnvelope style={{fontSize: '40px', color: '#000'}}/>
                        </div>
                        <div className={styles.text}>
                            Email
                        </div>
                    </a>
                </div>
            </main>
        </>
    )
}
