import React, {useEffect, useState} from 'react'
import axios from 'axios'
import styles from '../styles/Event.module.css'
import { RotateSpinner } from 'react-spinners-kit'
import Link from 'next/link'
import Head from 'next/head'


function Events({eventsInfo}) {

    // const [eventsInfo, setEventsInfo] = useState([])
    const [upcomingEvent, setUpcomingEvent] = useState([]);
    const [pastEvent, setPastEvent] = useState([]);
    const [value, setValue] = useState(0)
    const [allEvents, setAllEvents] = useState([])
    // const [loading, setLoading] = useState(false)
    const [error, setError] = useState('')
    // console.log(eventsInfo);

    useEffect(() => {
        console.log(eventsInfo);
        let upcoming = eventsInfo.filter(ev => ev.Status === "U")
        let past = eventsInfo.filter(ev => ev.Status === "P")
        setUpcomingEvent(upcoming)
        setPastEvent(past)
        setAllEvents([...upcoming])
    }, [])

    const upcomingFn = () => {
        setAllEvents(upcomingEvent)
        setValue(0)
    }

    const pastFn = () => {
        setAllEvents(pastEvent)
        setValue(1)
    }

    const trunc = (word) => {
        if (word.length > 10) {
            let w = word.slice(0, 13) + '...'
            return w 
        }
        return word
    }

    return (
        <>
        <Head>
        <title>CarPotal | Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="bgImage"></div> */}
        <div className={styles.tabs}>
            {/* <div className={styles.title}>
                <h2>Events</h2>
                <div className={styles.outline}></div>
            </div> */}
            <main className={styles.event}>
                <section className={styles.btn_container}>
                    <div className={`${styles.btn} ${value === 0 ? styles.active : ''}`} onClick={upcomingFn}>Upcoming Events</div>
                    <div className={`${styles.btn} ${value === 1 ? styles.active : ''}`} onClick={pastFn}>Past Events</div>
                </section>
                <section className={`${styles.main_content} ${styles.event_list}`}>
                    {
                        allEvents?.length === 0 ?
                        <div className={styles.single_event}>
                            <h2>Oops, No Events Here!</h2>
                        </div>
                         :
                        allEvents.map((ev, i) => {
                            return (
                                <div className={styles.single_event} key={i}>
                                    <div className="text">
                                        <h2>{trunc(ev.Title)}</h2>
                                        <p>{ev.Date}</p>
                                    </div>
                                    <div className={styles.link_btn}>
                                        <Link href={`/events/${ev.id}`}>More</Link>
                                    </div>
                                </div>
                            )
                        })
                    }
                </section>
            </main>
        </div>
        </>
    )

}

export const getServerSideProps = async (pageContext) => {
        let data = await axios.get('https://thecarportal.herokuapp.com/events/')
        let eventsInfo = await data.data.message
    return {
        props: {
            eventsInfo
        }
    }
}

export default Events
