import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>CarPotal | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.home}>
        <div className={styles.overlay}></div>
        <div className={styles.content}>
            <div className={styles.headline}>
                <h1>The Car Portal</h1>
                <h3>Your best bet in anything Automobile related</h3>
                <p>Founded in 2020, The car portal is a space that talks about cars, a space where you find anything about cars and car related stuff Started as an Instagram blog, expanding the horizon to car sales, fun YouTube videos, cool car merch</p>
            </div>
            <div className={styles.navs}>
                <div className={styles.nav__links}>
                    <Link href="/about" className={styles.btn_link}>
                        <a>About Us</a>
                    </Link>
                    <Link href="/carsales" className={styles.btn_link}>
                        <a>Auto-Mart</a>
                    </Link>
                    <Link href="/events" className={styles.btn_link}>
                        <a>Events</a>
                    </Link>
                    <Link href="/stores" className={styles.btn_link}>
                        <a>Store</a>
                    </Link>
                    <Link href="/login" className={styles.btn_link}>
                        <a className={styles.login}>Login</a>
                    </Link>
                </div>
            </div>
        </div>
    </main>
    </>
  )
}
